import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import logo from '../public/vercel.svg'
import dynamic from 'next/dynamic'
import { useState } from 'react';
import UserData from './userdata'
import useSWR from 'swr'

export default function Home() {
  const [toggle, setToggle] = useState(false)
  const changeToggle = ()=> {
    setToggle(prevState => !prevState)
  }
  const List = dynamic(()=> import('./list'),{
    loading: ()=> <p> now loading...</p>
  })

  //SWRーークライアントデータ取得
  // const fetcher = async (url) => {
  //   const res = await fetch(url)
  //   const data = await res.json()
  //   return data
  // }

  const fetcher = (url) => {
     return fetch(url).then((res) => res.json())
  }
  const { data, error } = useSWR(
    'https://jsonplaceholder.typicode.com/posts',
    fetcher
  );

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        <Link href="/about">
          Welcome to
        </Link>
        <Link　href="/post/pp">
        <a>動的ページへ</a>
        </Link>
      
        </h1>
          <button onClick={changeToggle}>Open List</button>
          {toggle && <List />}
    
        <h1>POSTデータ一覧</h1>
        <ul>
        {data.map((post)=> {
            return (        
                    <li key={post.id}>{post.title}</li>
            )
        })}
        </ul>

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image 
              src="/vercel.svg" 
              alt="Vercel Logo" 
              width={72} 
              height={16} />
          </span>
         
        </a>
      </footer>
    </div>
  )
}
